// <auto-generated />
using System;
using DBEmpresa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBEmpresa.Migrations
{
    [DbContext(typeof(NTSContext))]
    partial class NTSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DBEmpresa.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoID"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("DepartamentoID");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("DBEmpresa.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartamentoID")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentoID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("RolEmpleadoRolID")
                        .HasColumnType("int");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<int>("SubdepartamentoID")
                        .HasColumnType("int");

                    b.Property<int>("SubdepartamentoID1")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoID");

                    b.HasIndex("DepartamentoID");

                    b.HasIndex("DepartamentoID1");

                    b.HasIndex("RolEmpleadoRolID");

                    b.HasIndex("RolID");

                    b.HasIndex("SubdepartamentoID");

                    b.HasIndex("SubdepartamentoID1");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("DBEmpresa.Models.RolEmpleado", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("RolesEmpleados");
                });

            modelBuilder.Entity("DBEmpresa.Models.SubDepartamento", b =>
                {
                    b.Property<int>("SubdepartamentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubdepartamentoID"), 1L, 1);

                    b.Property<int>("DepartamentoID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubdepartamentoID");

                    b.HasIndex("DepartamentoID");

                    b.ToTable("Subdepartamentos");
                });

            modelBuilder.Entity("DBEmpresa.Models.Sueldo", b =>
                {
                    b.Property<int>("SueldoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SueldoID"), 1L, 1);

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SueldoID");

                    b.HasIndex("EmpleadoID");

                    b.ToTable("Sueldos");
                });

            modelBuilder.Entity("DBEmpresa.Models.Empleado", b =>
                {
                    b.HasOne("DBEmpresa.Models.Departamento", null)
                        .WithMany()
                        .HasForeignKey("DepartamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEmpresa.Models.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEmpresa.Models.RolEmpleado", "RolEmpleado")
                        .WithMany("Empleados")
                        .HasForeignKey("RolEmpleadoRolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEmpresa.Models.RolEmpleado", null)
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEmpresa.Models.SubDepartamento", null)
                        .WithMany()
                        .HasForeignKey("SubdepartamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEmpresa.Models.SubDepartamento", "Subdepartamento")
                        .WithMany("Empleados")
                        .HasForeignKey("SubdepartamentoID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("RolEmpleado");

                    b.Navigation("Subdepartamento");
                });

            modelBuilder.Entity("DBEmpresa.Models.SubDepartamento", b =>
                {
                    b.HasOne("DBEmpresa.Models.Departamento", "Departamento")
                        .WithMany("Subdepartamentos")
                        .HasForeignKey("DepartamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("DBEmpresa.Models.Sueldo", b =>
                {
                    b.HasOne("DBEmpresa.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("DBEmpresa.Models.Departamento", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Subdepartamentos");
                });

            modelBuilder.Entity("DBEmpresa.Models.RolEmpleado", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("DBEmpresa.Models.SubDepartamento", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
